---
# defaults file for web-app
github_repo_user: mikesnow79
webapp_github_ssh_uri: "git@github.com:{{github_repo_user}}/{{webapp_repo_name}}.git"
webapp_repo_name: play-blog-backend
webapp_install_dir: "{{master_app_dir}}/{{webapp_repo_name}}"

#TODO Move this higher up? front end too tied to backend?
frontend_install_dir: "{{master_app_dir}}/{{frontend_repo_name}}"
frontend_repo_name: play-blog-front-end
frontend_github_ssh_uri: "git@github.com:{{github_repo_user}}/{{frontend_repo_name}}.git"
frontend_dist_dir: "dist"
frontend_staticfile_dir: "{{frontend_install_dir}}/{{frontend_dist_dir}}"
webapp_local_conf_file: "{{webapp_install_dir}}/blog_backend/config/local.py"
fronted_config_file_entry: "    STATICFILES_DIRS = ['{{frontend_staticfile_dir}}']"