---
# tasks file for common-web

#- name: Install cmatrix
#  apt:
#    update_cache: yes
#    name: cmatrix
#  become: true

- name: Begin Message
  debug:
    msg: "Beginning Main Site Playbook"

- name: Set App Name
  debug:
    msg: "Appname is {{ app_name }}"

- name: create master app directory
  file:
    path: "{{master_app_dir}}"
    state: directory