---
# tasks file for web-app django setup

- name: Begin Message
  debug:
    msg: "Beginning Django dependency Playbook"

- name: clone django git repo
  git:
    repo: "{{webapp_github_ssh_uri}}"
    dest: "{{webapp_install_dir}}"
    clone: yes
    update: yes
#    force: yes

- name: clone front-end repo
  git:
    repo: "{{frontend_github_ssh_uri}}"
    dest: "{{frontend_install_dir}}"
    clone: yes
    update: yes
#    force: yes

- name: install python requirements
  pip:
    requirements: "{{webapp_install_dir}}/requirements.txt"
    virtualenv: "{{user_venv_dir}}"

- name: TODO copy django secret fake to postactivate script
  debug:
    msg: "Currently manually sourcing the secret key locally"

- name: Run django migrate on app
  django_manage:
    command: migrate
    app_path: "{{webapp_install_dir}}"
    virtualenv: "{{user_venv_dir}}"

- name: Add backend_dest_Dir to config
  lineinfile:
    path: "{{webapp_local_conf_file}}"
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: '{{fronted_config_file_entry}}'

- name: install npm dependencies
  shell: npm install
  args:
    chdir: "{{frontend_install_dir}}"

- name: run npm run build in dest frontend
  shell: npm run build
  args:
    chdir: "{{frontend_install_dir}}"

- name: Run django collectstatic on app
  django_manage:
    command: collectstatic
    app_path: "{{webapp_install_dir}}"
    virtualenv: "{{user_venv_dir}}"
